
name: Using Actions
on: [push, workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: List directories
              run: ls -la
            - name: Setup Node
              uses: actions/setup-node@v4
            - name: Trigger install
              run: npm ci
            - name: Run tests
              run: npm test

