name: "07 - Using Expressions"
on:
  push:
  workflow_dispatch:
      inputs:
        debug:
          description: "Event-Trigger"
          type: boolean
          default: false
jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        if: ${{inputs.debug == true}}
        run: |
          echo "Triggered by: github.event_name"
          echo "Branch"
          echo "Commit SHA: "
          echo "Runner OS"

